### ISSUE TITLE
Benchmarking is not shown properly in notebooks

### ISSUE THREAD

**Issue by saattrupdan** [saattrupdan/ScandEval#23]
When using the `Benchmark` class to benchmark models in a notebook, a lot of output appears:
- The config of the model
- The architecture of the model
- Caching logs
- A block of text starting with `***** Running training *****`
- A message after each finetuning: `Training completed. Do not forget to share your model on huggingface.co/models =)
`
- A block of text starting with `***** Running evaluation *****`

All of these should be removed. It seems like the the `set_verbosity_error` from the `transformers` library does not work in notebooks.

**Comment by KappaDistributive** [comment]
For what it's worth: I can't seem to reproduce this bug. Neither in a local Jupyter Lab nor in Google Colab.

Can this be closed?

**Comment by saattrupdan** [comment]
> For what it's worth: I can't seem to reproduce this bug. Neither in a local Jupyter Lab nor in Google Colab.
> Can this be closed?

I just tried to test this as well, and it seems to have been solved in the newer versions! Great stuff, closing 🙂
