### ISSUE TITLE
Evaluating private HuggingFace models

### ISSUE THREAD

**Issue by peregilk** [saattrupdan/ScandEval#25]
It would be great if ScandEval also could be used for evaluating private HuggingFace models. This could probably be done by passing along the flag «use_auth_token=True» to the .from_pretrained method. This allows the user to log in with huggingface-cli. This will store the auth token locally. It can also be passed on directly but personally I find this less convenient.

**Comment by saattrupdan** [comment]
Added this in [v4.0.0](https://github.com/saattrupdan/ScandEval/releases/tag/v4.0.0).
