### ISSUE TITLE
Add mdeberta-v3-base

### ISSUE THREAD

**Issue by KennethEnevoldsen** [saattrupdan/ScandEval#30]
A potential model to include which is currently missing is the [multilingual deBERTa](https://huggingface.co/microsoft/mdeberta-v3-base).

Best,
@kennethenevoldsen and @maltehb

**Comment by saattrupdan** [comment]
@KennethEnevoldsen Feel free to benchmark it using the `scandeval` package and send a PR to [the leaderboard repo](https://github.com/ScandEval/scandeval.github.io). It takes roughly a week to benchmark a model and I've already got a long queue of models to benchmark, so delegating the work would be great.

IIRC, the issue with mDeBERTa was that its tokeniser wasn't properly supported in the `transformers` library, but that might be alright now.

**Comment by saattrupdan** [comment]
@KennethEnevoldsen It has been added to the new leaderboard now, with the new release 🙂 

See https://scandeval.github.io/language-model-benchmark/
