### ISSUE TITLE
Add mT5

### ISSUE THREAD

**Issue by KennethEnevoldsen** [saattrupdan/ScandEval#31]
Currently, there is no evaluation of the mT5 models

**Comment by saattrupdan** [comment]
mT5 is a generative model and thus doesn't support evaluation on classification tasks, AFAIK.

**Comment by KennethEnevoldsen** [comment]
I depends on how you phrase it:

"I am very happy" -> T5 -> "positive"

**Comment by saattrupdan** [comment]
Aha! Well, that would require setting the `scandeval` package up to deal with generative models in this way, which is substantial and non-trivial. But I can create a separate issue on that, in which we could discuss how it could be set up 👍

**Comment by KennethEnevoldsen** [comment]
i think that is a great idea. Also, allow others to contribute.
