### ISSUE TITLE
Invalid model name does not raise an error or a warning

### ISSUE THREAD

**Issue by KennethEnevoldsen** [saattrupdan/ScandEval#57]
When running the following line of code:
```
CUDA_VISIBLE_DEVICES=2 scandeval --model-id nota/model --language da
```

I would expect the model to throw an error like "could not find model in hub", but instead it simply skips all the benchmarks as seen here:
```
2023-07-09 09:02:42,441 [INFO] <scandeval.benchmarker>
↳ Benchmarking nota/model on the truncated version of AngryTweets
2023-07-09 09:02:44,589 [INFO] <scandeval.benchmarker>
↳ nota/model could not be benchmarked on the truncated version of AngryTweets. Skipping.
2023-07-09 09:02:44,589 [INFO] <scandeval.benchmarker>
↳ Benchmarking nota/model on the truncated version of DaNE
2023-07-09 09:02:46,616 [INFO] <scandeval.benchmarker>
↳ nota/model could not be benchmarked on the truncated version of DaNE. Skipping.
2023-07-09 09:02:46,616 [INFO] <scandeval.benchmarker>
↳ Benchmarking nota/model on the Danish part of ScaLA
2023-07-09 09:02:48,447 [INFO] <scandeval.benchmarker>
↳ nota/model could not be benchmarked on the Danish part of ScaLA. Skipping.
2023-07-09 09:02:48,447 [INFO] <scandeval.benchmarker>
↳ Benchmarking nota/model on the Danish part of the truncated version of ScandiQA
2023-07-09 09:02:50,898 [INFO] <scandeval.benchmarker>
↳ nota/model could not be benchmarked on the Danish part of the truncated version of ScandiQA. Skipping.
2023-07-09 09:02:50,898 [INFO] <scandeval.benchmarker>
↳ Benchmarking nota/model on the speed estimation benchmark
2023-07-09 09:02:51,259 [INFO] <scandeval.benchmarker>
↳ nota/model could not be benchmarked on the speed estimation benchmark. Skipping.
```

**Comment by saattrupdan** [comment]
Try running it with the `--raise-errors` flag and see if that solves it 🙂

**Comment by KennethEnevoldsen** [comment]
Solves it. Should have tested that. Might be worth adding the error to the output. it to the output. Something like:

> nota/model could not be benchmarked on the speed estimation benchmark. Skipping.
> **↳ Failed with the error: "The model nota/model does not exist on the Hugging Face Hub".**

You could even add:
> To see the full stacktrace run scandeval using the --raise-errors flag

Though it might be too verbose.

**Comment by saattrupdan** [comment]
Noted, and good idea!

**Comment by saattrupdan** [comment]
@KennethEnevoldsen Just FYI, if you run the evaluation with the `--verbose` flag then the errors will also be displayed, in the manner in which you describe. What you're proposing is whether this should be default, I guess?
