### ISSUE TITLE
Cache interference issues when testing two models at once

### ISSUE THREAD

**Issue by KennethEnevoldsen** [saattrupdan/ScandEval#59]
Seems like the cache systems interferes with other running sessions of scandeval as it seems to delete the checkpoint of another runs.
Thus does not allow for workflow like:
```
CUDA_VISIBLE_DEVICES=1 scandeval --model-id MODEL1 --language da --raise-errors
# on a separate instance:
CUDA_VISIBLE_DEVICES=2 scandeval --model-id MODEL2 --language da --raise-errors
```

Naturally I could use multiple `--model-id` flags, but I wanted them to run each on their own GPUs.

A simple solution is to naturally do it in different folders and thus create two scandeval caches (which is what I am doing now).
However I wanted to suggest to nest the cache folder such that the structure is:

```
.scandeval_cache/model_id/checkpoint-270
```

as opposed to:

```
.scandeval_cache/checkpoint-270
```

I might have missed other important considerations

**Comment by saattrupdan** [comment]
Great suggestion! Are you able to create a PR with the change?

**Comment by KennethEnevoldsen** [comment]
Have added a reminder on it ;) Shouldn't take too long
