### ISSUE TITLE
Bug in maximum sequence length

### ISSUE THREAD

**Issue by KennethEnevoldsen** [saattrupdan/ScandEval#62]
When running a model I get that the maximum sequence length is 8, which for this model is clearly wrong:
```
2023-07-12 22:31:48,721 [INFO] <scandeval.benchmarker>
↳ Benchmarking chcaa/dfm-encoder-large-v1 on the truncated version of AngryTweets
2023-07-12 22:32:41,631 [INFO] <scandeval.benchmark_dataset>
↳ The model has 355,090,435 parameters, a vocabulary size of 50,000 and a maximum sequence length of 8.
```

When running it in the debugger I found that it seems to be caused by the line `model.config.max_position_embeddings - tokenizer.pad_token_id - 1` in the code:

```python
    # Add the max length derived from the position embeddings
    if (
        hasattr(model.config, "max_position_embeddings")
        and hasattr(tokenizer, "pad_token_id")
        and tokenizer.pad_token_id is not None
    ):
        all_max_lengths.append(
            model.config.max_position_embeddings - tokenizer.pad_token_id - 1
        )
```

For this case we obtain something like: 512 - 503 - 1 = 8

The intended calculation might have been something akin to:
```
model.config.max_position_embeddings - int(bool(tokenizer.pad_token_id)) - 1
```
While here we get: 512 -1 - 1 = 510.

I have created that fix [here](https://github.com/KennethEnevoldsen/ScandEval/tree/fix_max_seq_length), but I don't think that is the ideal fix though. tokenizer.pad_token_id could be 0 and you already check whether it is None so might be better to simply use

```
model.config.max_position_embeddings - 2
```

However, I am unsure if I am missing the intention of this snippet. The bug seems to have been introduced [here](https://github.com/saattrupdan/ScandEval/commit/2abcdd5bb71ebc3d8d40385f03c523ec67411fd2).

**Comment by saattrupdan** [comment]
To be honest, I can't remember what exactly caused that issue either. In the branch that I'm currently developing on (`feat/add-openai-evaluation`) I've simply removed the `- tokenizer.pad_token_id - 1` bit, and it works just fine. But I haven't looked into this properly.
