### ISSUE TITLE
Add model: roberta-base-danish

### ISSUE THREAD

**Issue by KennethEnevoldsen** [saattrupdan/ScandEval#67]
Noticed that the model:
https://huggingface.co/DDSC/roberta-base-danish

was missing.

**Comment by saattrupdan** [comment]
I see it in there? Can you double check?

<img width="1213" alt="Screenshot 2023-11-10 at 11 20 28" src="https://github.com/saattrupdan/ScandEval/assets/47701536/b4be0b02-1fc5-41b6-9dd0-4eb721c29a42">

**Comment by KennethEnevoldsen** [comment]
ahh, you are right. I was looking for:
https://huggingface.co/flax-community/roberta-base-danish

But it seems like the model has been renamed. Should have noticed when I copied in the link.
